//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNhaXinh.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportBillDetail
    {
        public string ImpDID { get; set; }
        public string ImpID { get; set; }
        public string ProID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ImportPrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> ToTalMoney { get; set; }
    
        public virtual ImportBill ImportBill { get; set; }
        public virtual Product Product { get; set; }
    }
}
