//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNhaXinh.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportBill()
        {
            this.ImportBillDetails = new HashSet<ImportBillDetail>();
        }
    
        public string ImpID { get; set; }
        public string ProID { get; set; }
        public int UserID { get; set; }
        public string ImpDate { get; set; }
        public Nullable<int> MoneyTotal { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Pay { get; set; }
        public string PayID { get; set; }
    
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportBillDetail> ImportBillDetails { get; set; }
        public virtual User_ User_ { get; set; }
    }
}
