//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNhaXinh.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string NewID { get; set; }
        public string Title { get; set; }
        public string AddID { get; set; }
        public string Content { get; set; }
        public string PublicDate { get; set; }
    }
}
