//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNhaXinh.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrdID { get; set; }
        public string CusID { get; set; }
        public string OrderDate { get; set; }
        public string Status { get; set; }
        public string ReceivingAddress { get; set; }
        public string ReceivingPhone { get; set; }
        public Nullable<int> MoneyTotal { get; set; }
        public string Note { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
