//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNhaXinh.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ImportBillDetails = new HashSet<ImportBillDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Prices = new HashSet<Price>();
            this.CartDetails = new HashSet<CartDetail>();
        }
    
        public string ProID { get; set; }
        public string CatID { get; set; }
        public string Metatitle { get; set; }
        public string ProName { get; set; }
        public string ProDescription { get; set; }
        public string ProColor { get; set; }
        public string Materials { get; set; }
        public string Size { get; set; }
        public string ProImage { get; set; }
        public string Tags { get; set; }
        public string MoreImage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string MetaDescriptions { get; set; }
        public string Displayhome { get; set; }
        public bool Status { get; set; }
        public Nullable<int> inventory { get; set; }
        public Nullable<int> sold { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportBillDetail> ImportBillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Prices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDetail> CartDetails { get; set; }
    }
}
