//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNhaXinh.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDetail
    {
        public string RoDID { get; set; }
        public string RooID { get; set; }
        public string RoDName { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string RoDDescription { get; set; }
        public string Details { get; set; }
        public bool Status { get; set; }
        public string Silde { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
