//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNhaXinh.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public string UserEmail { get; set; }
        public string UserAddress { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Identification { get; set; }
        public Nullable<System.DateTime> DateofIssueinIDcard { get; set; }
        public string Degree { get; set; }
        public string Gender { get; set; }
        public string PlaceofIssueofIdentityCard { get; set; }
        public string MaritalSatus { get; set; }
        public string Password { get; set; }
        public string UserImage { get; set; }
        public string Position { get; set; }
        public bool Status { get; set; }
    }
}
